### ISSUE TITLE
[bug] error when run in native english system

### ISSUE THREAD

**Issue by gregist** [nondanee/weiboPicDownloader#1]
```
Traceback (most recent call last):
  File "weiboPicDownloader.py", line 221, in <module>
    main()
  File "weiboPicDownloader.py", line 131, in main
    home_path = os.path.realpath(raw_input_fit("Φ»╖Φ╛ôσàÑσ¢╛τëçσ¡ÿσé¿Σ╜ìτ╜«: "))
  File "weiboPicDownloader.py", line 31, in raw_input_fit
    prompt = string.decode("utf-8").encode(sys.stdin.encoding or locale.getpreferredencoding(True))
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-8: character maps to <undefined>
```
I translated the prompts langage in the code to English and it now run perfectly fine.

**Comment by nondanee** [comment]
I am sorry to reply for your issue almost one week after
because i didn't "watch" this repo and no email remind 😭

Is it english version of Windows?
I test on the linux with en-us locale but it works fine.

Unicode problem is really annoying in python 2
Maybe i should turn to python 3 😶

**Comment by nondanee** [comment]
@gregist 
well, now in dev branch
program has no chinese prompts, but will displays nickname maybe in chinese
and it is compatible with both python2 and python3
if it still run with unicode error, you can try it in python3 environment
thank you for opening the first issue
i intend to close it
