### ISSUE TITLE
不能识别以“-”开头的微博昵称

### ISSUE THREAD

**Issue by kybom** [nondanee/weiboPicDownloader#12]
微博昵称规则：设置或修改的昵称，请在4-30个字符，支持中英文、数字、“_”和减号。
微博昵称可以包含减号，以减号开头的微博昵称无法识别
```
root@ubuntu:~/workspace/rep/weiboPicDownloader# python weiboPicDownloader.py -u -CKG48-曾佳  -v -s 5
usage: weiboPicDownloader [-h] [-u user] [-us users [users ...]] [-f file]
                          [-d directory] [-s size] [-v] [-o]
weiboPicDownloader: error: argument -u: expected one argument

```

**Comment by kybom** [comment]
目前的办法是从文件或交互式窗口输入

**Comment by nondanee** [comment]
我去翻文档了，文档里有这个，但是是负数的，试了下负数可以用它的解决方法，不是负数就不行
https://docs.python.org/3/library/argparse.html#arguments-containing
好像没办法解决，除非我自己解析`sys.argv`，感觉有点犯不着
所以还是从文件导入，或者用uid来解决吧

**Comment by fireattack** [comment]
现在的实现好像不是很完美，如果用户名的开头和其他switch重复的话还是会出错

比如`weiboPicDownloader.py -u -CKG48-曾佳` OK，但是 `weiboPicDownloader.py -u -cKG48-曾佳`就报错了。。

**Comment by nondanee** [comment]
@fireattack 修了
