### ISSUE TITLE
cannot download all images？

### ISSUE THREAD

**Issue by Mrxuefei** [nondanee/weiboPicDownloader#14]
hi,I run your code, and I found it can only download part of albums.Is that my setting problem?

**Comment by nondanee** [comment]
It's not your fault.

Accurately, the album is not the true user album (whose entrance is on user profile page in pc viewing).
Program gets the approximate data by making requests for user's whole weibo feed, 
and pick up resources from every weibo if images or videos exist. 

The amount is decided by data from weibo's feed api. And I don't know what limitation this api has.
Seriously speaking, it's not a public api and I do request forgery "illegally".

**Comment by nondanee** [comment]
No whole weibos causes no whole album.
I knew this issue before and made a "practically get ??? weibos" message in the program.
I also did test on my own account. Request with my cookie can get more weibos and images but not all.

Really confusing...
