### ISSUE TITLE
爬取多用户图片

### ISSUE THREAD

**Issue by woshizhangcheng** [nondanee/weiboPicDownloader#2]
你好,现在我要爬取多个用户的话,思路应该怎么来走,或者说得到多用户的uid和id名后进行爬取图片,谢谢

**Comment by nondanee** [comment]
现在一次只能爬一个用户的图片，多用户的话多开几个窗口呗😂
做多用户的话逻辑会变很多，在现在的基础上不太好改代码
如果真有大批量的需求
建议用 [ningshu/weiboPicDownloader](https://github.com/ningshu/weiboPicDownloader) 项目
不过这个repo在新浪接口变更后还没更新过，等下我会pr给他。
