### ISSUE TITLE
可以设置下载某个时段的微博吗？

### ISSUE THREAD

**Issue by fuyazhou** [nondanee/weiboPicDownloader#25]
比如我想下载最近两个月的图片？这个怎么实现？

**Comment by nondanee** [comment]
[L178-179](https://github.com/nondanee/weiboPicDownloader/blob/dev/weiboPicDownloader.py#L178)
要改，加个比较时间大小的break判断就行了。

不过我看了下这个接口给的时间做了Friendly Date Ranges，所以也不是准确时间

**Comment by fuyazhou** [comment]
en, nice, thanks

**Comment by nondanee** [comment]
之前commit过了😂，现在是[L181](https://github.com/nondanee/weiboPicDownloader/blob/dev/weiboPicDownloader.py#L181)
