### ISSUE TITLE
某一个用户无法爬取

### ISSUE THREAD

**Issue by Siriuscw** [nondanee/weiboPicDownloader#26]
![image](https://user-images.githubusercontent.com/13619509/45544278-75022b80-b849-11e8-8530-5aa9324d7a2c.png)

**Comment by nondanee** [comment]
试了下是因为没有登录状态😔

**Comment by Siriuscw** [comment]
诶？什么登陆状态？我登陆之后还是失败的呢。。

**Comment by nondanee** [comment]
就是请求需要带cookie。我这个不是selenium驱动的，你在浏览器登录和这个程序请求无关

**Comment by Siriuscw** [comment]
哦哦谢谢大佬，还有个问题就是为什么爬其他用户的时候就可以不用带cookie呢？

**Comment by nondanee** [comment]
渣浪的限制😂我也不知道具体是怎样的，用的是微博H5(PWA)版的API，理论上是支持免登录浏览的

**Comment by nondanee** [comment]
@Siriuscw 设置cookie的方法写在README里了

**Comment by Siriuscw** [comment]
谢谢√

**Comment by Siriuscw** [comment]
![image](https://user-images.githubusercontent.com/13619509/45584243-bc98be00-b902-11e8-8382-28ad7f00a275.png)emmmm大佬我刚开始学爬虫，有好多原理都不太懂，正在拿这个项目研究，但基本上就算出错了也不知道要怎么下手解决，可以问问您是怎么学习的吗

**Comment by nondanee** [comment]
emmm，多试几次看看，应该是可以成功的😂
实话说其实这个项目里面大部分代码和爬虫都无关😂
issue说不方便的话可以直接邮件发我你的qq/wechat/tg等等都行😂

**Comment by Siriuscw** [comment]
你好，刚向你outlook邮箱发了封邮件，但是直接从git这个issue发出去的，才看到格式可能有点糟糕，还望见谅😀

**Comment by nondanee** [comment]
👌
