### ISSUE TITLE
增不增加cookie对下载结果有影响吗？

### ISSUE THREAD

**Issue by kybom** [nondanee/weiboPicDownloader#27]
增加cookie可以下载到更多的内容吗？是否每次下载都要重新获取cookie?

**Comment by nondanee** [comment]
某些情况下是的，见[#26](https://github.com/nondanee/weiboPicDownloader/issues/26)，只有带cookie才行
你也可以带上cookie试试practically get和total一不一样
登录状态有时限，看多久下载一次，过好多天的话就需要重新获取cookie了
大批量的话建议用小号的cookie，万一号被封了呢==
