### ISSUE TITLE
invalid account 

### ISSUE THREAD

**Issue by wankio** [nondanee/weiboPicDownloader#33]
python weibopicdownloader.py -u 3156359295
1/1 Tue Jan 22 15:47:57 2019
invalid account 3156359295
------------------------------
bye bye

old version is stucked on analysis so i just downloaded newer version(2months ago) and now it have this problem. So i just run it without python and then rerun it with python ,now it work but still stucked in analysing xxx/xxxx, i dont know why

Thank

**Comment by nondanee** [comment]
sticking at analysing because request triggers weibo's anti-scraping mechanism (418 i'm a teapot)
there is no other solution instead of waiting for unblocking
try the latest dev branch version please

**Comment by wankio** [comment]
it worked, ty

**Comment by nondanee** [comment]
👌
