### ISSUE TITLE
关于重命名，老兄可以开放个option来支持一下图片的重命名吗？

### ISSUE THREAD

**Issue by Geolage** [nondanee/weiboPicDownloader#35]
如题。
用微博本身的文件名看着很不舒服啊，如果可以时间和微博描述来做文件名的话就好了，这样方便管理。

**Comment by Geolage** [comment]
@nondanee

**Comment by nondanee** [comment]
好的
时间不好做，因为接口不给准确时间(只提供 "10小时前" 这样的)
微博描述就是 mid 和 bid 了，应该是自增的，可能是时间顺序，不确定

**Comment by Geolage** [comment]
哦，不好意思，我说错了。其实我所谓的“描述”应该就是微博文字来的，可以截取n个字符串来命名。

**Comment by nondanee** [comment]
那很容易命名冲突啊

**Comment by Geolage** [comment]
哈哈，不会的，如果用户没有其它命名参数的话，那就加个默认前/后缀呗，比如index。

**Comment by nondanee** [comment]
index 肯定要加的，九图要编号
取 n 个字符的话不同微博也不唯一，overwrite 选项会失效，比如文字开头都是话题名字 "#岚2020年底终止团体活动#" 这样的

**Comment by Geolage** [comment]
嗯，对的！所以这个字符串截取长度的值，可以作为maxLength来配置。

**Comment by nondanee** [comment]
https://github.com/nondanee/weiboPicDownloader/blob/44bc0f8fae7769e3ee2c39f73e7bca3f0314b1fa/weiboPicDownloader.py#L197-L201

要做命名规则太复杂，只留了接口，需要其它的命名格式直接改代码吧
item 中包含 url, index, mid, bid, text, type
注: 取到的 text 里会有 html 标记，不登录拿不到 raw_text 字段
