### ISSUE TITLE
希望能增加下载单条微博的功能

### ISSUE THREAD

**Issue by aliliao** [nondanee/weiboPicDownloader#37]
如题，希望能增加下载单条微博的功能，这样就不用老点另存为了。

**Comment by nondanee** [comment]
但这个 repo 是相册下载啊，为什么要有这个功能呢？

**Comment by aliliao** [comment]
emmm， 我的意思是希望可以支持下载单条微博的配图，因为有的时候可能不需要下载全部相册。

**Comment by nondanee** [comment]
@aliliao 
支持了，你这样加参数就是下载单条微博 `-u <用户名/ID> -b <微博ID>`
