### ISSUE TITLE
可以将下载的图片分为每个微博一个目录存放吗

### ISSUE THREAD

**Issue by yuezy3** [nondanee/weiboPicDownloader#38]
下载某博主的所有相册，好像是将所有图片放在一起，能不能弄一个选项使得可以将一条博客下的图片放在一个目录中，目录名字从博客中提取。

**Comment by nondanee** [comment]
https://github.com/nondanee/weiboPicDownloader/issues/35#issuecomment-461115337
取名很麻烦，留了改变命名规则的接口，你可以自己改
