### ISSUE TITLE
Feature request: download by latest successful try

### ISSUE THREAD

**Issue by afterdelight** [nondanee/weiboPicDownloader#40]
Could you make the script only parse and download data by latest successful download (by date)? (ex: latest successful download: 20190606, downloaded data 100% successful). Since they are a lot of unused images and videos from target account, I don't want to keep repeating deleting them. It also will save parsing time from account with large amounts of images and videos.  Thank you :)

**Comment by nondanee** [comment]
Use the `-b` option

**Comment by afterdelight** [comment]
Can you explain how -b option works in detail? I don't really understand.

**Comment by nondanee** [comment]
[The weibo with id 4382139325785907](https://m.weibo.cn/detail/4382139325785907) was posted at 2019/06/11 23:28

`-b 4382139325785907:`
means extracting weibos whose id large than 4382139325785907
also equal to extracting weibos sent after 2019/06/11 23:28

`-b :4382139325785907`
means before 2019/06/11 23:28

`-b 4382139325785907:4388622797092643`
extracting weibos between these two weibos were sent

**Comment by afterdelight** [comment]
Sorry, I don't really understand how to get the post id. I use .com version, weibo.com/u/xxxxxx like in this post.
https://stackoverflow.com/questions/22563468/how-can-i-get-the-id-of-some-weibo-post.

**Comment by nondanee** [comment]
Well, it's hard to get the mid of post in Weibo PC site (www.weibo.com)
But now you can directly use "bid" in `-b` option

For the example in your reference url:
http://www.weibo.com/1833141401/AC1klvp6U?mod=weibotime

The "bid" of this post is `AC1klvp6U`

**Comment by afterdelight** [comment]
It works! Thank you. Btw, I have another suggestion on https://github.com/nondanee/weiboPicDownloader/issues/39#issuecomment-501670903. I don't think you saw it.

**Comment by nondanee** [comment]
Now it supports https://github.com/nondanee/weiboPicDownloader/commit/a92e249275e3e1a7e54dd1ee8a2ff7dbe88fe77a
Thanks for you suggestion
