### ISSUE TITLE
Support date format for boundary option

### ISSUE THREAD

**Issue by afterdelight** [nondanee/weiboPicDownloader#41]
Hi, thanks for bid support but I think it's still too much hassle because I must open the page and check the unique bid id. How about simpler solution, support for -b 'date format'. Example: ' -b 20190606: '. Download only posts after 2019 06 06 date. Thanks!

**Comment by nondanee** [comment]
Sorry
date format is not unique, like `20190606`, `190606`, `2019-06-06`, `2019/06/06`, `2019.6.6`
I can't parse it

**Comment by afterdelight** [comment]
Oh okay then, thanks anyway.
