### ISSUE TITLE
每次下载都下不完全

### ISSUE THREAD

**Issue by Lannist** [nondanee/weiboPicDownloader#43]
大佬好，首先感谢你的代码。
我发现每次用这个代码下某一用户的微博图都下不完全，发现主要原因是微博浏览的不全。
有些明明发了600多条微博，我这最终只能抓500条，有的发了1500条，我这只能practically900多条， 请问这个有具体解决办法吗。
非常感谢

**Comment by nondanee** [comment]
带上 cookie 试一下

**Comment by Lannist** [comment]
有效下载量从520/623  提高到了606/623。提高了一些

**Comment by nondanee** [comment]
1. 微博总数可能不准，https://github.com/nondanee/weiboPicDownloader/issues/15#issuecomment-385711458
3. 可能中间有空页，你可以手动请求后面几页确认一下
2. 也可能是 H5 (PWA) 版的限制，你自己在浏览器上看总数也不足

**Comment by Lannist** [comment]
> 1. 微博总数可能不准，[#15 (comment)](https://github.com/nondanee/weiboPicDownloader/issues/15#issuecomment-385711458)
> 2. 可能中间有空页，你可以手动请求后面几页确认一下
> 3. 也可能是 H5 (PWA) 版的限制，你自己在浏览器上看总数也不足

![788D1E7E-E1CE-4732-B5FD-EFC63250B6D2](https://user-images.githubusercontent.com/6830752/62520880-0c58de80-b861-11e9-9b50-3cb17a5f90f6.png)

您好，我这里报的log如上图所示。 跟原因1的现象差距较大，应该不是1的原因。

第三条原因说是PWA版限制，但为啥能够找到2541条微博，确只能浏览到2008.

至于您说的第2条原因，我没理解，请问如何手动进行后面几页的确认，具体意思是我去一条条翻原po的状态，再和下载的图片对比，看是否中间的一些微博缺失了吗？

**Comment by nondanee** [comment]
2541 只是个计数，新浪并没有说能找到 2541 条微博啊
新浪只返回 2008 条，那么你就只能浏览到 2008 条
为什么，要问新浪了

第二个原因，按照你截图里的例子
```https://m.weibo.cn/api/container/getIndex?count=25&page=90&containerid=107603{id}```
比如 90 是空页
```https://m.weibo.cn/api/container/getIndex?count=25&page=91&containerid=107603{id}```
比如 91 有内容
```https://m.weibo.cn/api/container/getIndex?count=25&page=92&containerid=107603{id}```
或者 90 91 是空页， 92 有内容

为什么是空页，我也不知道
可能有什么反爬机制吧

哦我看了下我自己的微博，PC WEB 上也是不足数的，理论上也应该每页都是 45 条，加上最后一页正好是微博总数，但我已经翻到一页不足 45 条的了，所以肯定不足...

这个问题没什么好纠结的......

**Comment by Lannist** [comment]
> 2541 只是个计数，新浪并没有说能找到 2541 条微博啊
> 新浪只返回 2008 条，那么你就只能浏览到 2008 条
> 为什么，要问新浪了
> 
> 第二个原因，按照你截图里的例子
> `https://m.weibo.cn/api/container/getIndex?count=25&page=90&containerid=107603{id}`
> 比如 90 是空页
> `https://m.weibo.cn/api/container/getIndex?count=25&page=91&containerid=107603{id}`
> 比如 91 有内容
> `https://m.weibo.cn/api/container/getIndex?count=25&page=92&containerid=107603{id}`
> 或者 90 91 是空页， 92 有内容
> 
> 为什么是空页，我也不知道
> 可能有什么反爬机制吧
> 
> 哦我看了下我自己的微博，PC WEB 上也是不足数的，理论上也应该每页都是 45 条，加上最后一页正好是微博总数，但我已经翻到一页不足 45 条的了，所以肯定不足...
> 
> 这个问题没什么好纠结的......

好的，理解了。非常感谢你的认真讲解。
