### ISSUE TITLE
Download media by keywords

### ISSUE THREAD

**Issue by afterdelight** [nondanee/weiboPicDownloader#46]
Using https://s.weibo.com/, I want to download all post with keyword 'apple' or tag apple. Or all post with keyword/tag apple from specific user. Is this possible?

**Comment by nondanee** [comment]
Possible to do this filtering for specific user

Add a line like this
```python
if 'apple' not in mblog['text']: continue
```
after
https://github.com/nondanee/weiboPicDownloader/blob/509cc4e2ca21d310b8a73fbcff199e045f945e99/weiboPicDownloader.py#L230

**Comment by afterdelight** [comment]
Thanks, it worked. But it seems it can't fetch all the post since the account been created. only around up to one year of medias grabbed.

**Comment by nondanee** [comment]
That's limited by weibo
Maybe using cookie (`-c`) will give you some help

**Comment by afterdelight** [comment]
I used -c and the resuilt is same, only up to one year. I used cookie from 'SUB' from weibo.com since i can't find SUB cookie on weibo.cn.

I remembered when I first using this program it can fetch till the first post of when the page created. Now its limited.

**Comment by nondanee** [comment]
It should be OK to use the `SUB` cookie from weibo.com

But I can do nothing if sina limited the data
Sorry
