### ISSUE TITLE
Can`t download the latest photos.

### ISSUE THREAD

**Issue by cor961** [nondanee/weiboPicDownloader#48]
I run this program in a NAS, it's basically working properly, and I start it regularly to download the latest pictures.

But there is a problem, a Weibo account with a lot of pictures (more than 3165), I tried the-f or-u parameter, can not download the latest photos, only the-u-b parameter can be downloaded properly. This problem did not occur when I first started using it a few months ago, but I also had the same problem testing with older versions of the program.

Is there a certain number of restrictions in this program or Weibo site settings that cause this problem?

Other accounts downloaded in turn using the-f parameter are normal.

The error log is usually like this:

[Kanalysing weibos... 25/756(#1)
[Kanalysing weibos... 49/756(#2)
[Kanalysing weibos... 72/756(#3)
[Kanalysing weibos... 95/756(#4)
[Kanalysing weibos... 120/756(#5)
[Kanalysing weibos... 145/756(#6)
[Kanalysing weibos... 170/756(#7)
[Kanalysing weibos... 195/756(#8)
[Kanalysing weibos... 219/756(#9)
[Kanalysing weibos... 244/756(#10)
[Kanalysing weibos... 269/756(#11)
[Kanalysing weibos... 294/756(#12)
[Kanalysing weibos... 319/756(#13)
[Kanalysing weibos... 344/756(#14)
[Kanalysing weibos... 369/756(#15)
[Kanalysing weibos... 393/756(#16)
[Kanalysing weibos... 418/756(#17)
[Kanalysing weibos... 443/756(#18)
[Kanalysing weibos... 468/756(#19)
[Kanalysing weibos... 493/756(#20)
[Kanalysing weibos... 518/756(#21)
[Kanalysing weibos... 542/756(#22)
[Kanalysing weibos... 567/756(#23)
[Kanalysing weibos... 589/756(#24)
[Kanalysing weibos... 614/756(#25)
[Kanalysing weibos... 639/756(#26)
[Kanalysing weibos... 664/756(#27)
[Kanalysing weibos... 688/756(#28)
[Kanalysing weibos... 712/756(#29)
[Kanalysing weibos... 726/756(#30)
[Kfinish analysis 726/756(#31)
practically scan 726 weibos, get 3221 resources

[Kall tasks done 3221/3221(100%)
success 3220, failure 1, total 3221
automatic retry 1

[Kdownloading... 0/1(0%)
[Kdownloading... 0/1(0%)
[Kdownloading... 0/1(0%)
[Kall tasks done 1/1(100%)
success 0, failure 1, total 1
automatic retry 2

[Kdownloading... 0/1(0%)
[Kdownloading... 0/1(0%)
[Kdownloading... 0/1(0%)
[Kall tasks done 1/1(100%)
success 0, failure 1, total 1
https://wx4.sinaimg.cn/large/0065Jim5ly1g8cz10ucx0j30u01400zo.jpg failed

By the way, I can access the links that are usually displayed.

Thank you very much for your creation.

**Comment by nondanee** [comment]
`-b` option only applies an id range filter on the same feeds without `-b` option
I have no idea why using `-u -b` can download properly

There is no restriction in program
But I'm not sure whether the feeds from API are limited by weibo official or not

Running program with your cookie may work
Please test
