### ISSUE TITLE
Adding feature of pulling image/video from a specific date on

### ISSUE THREAD

**Issue by hao-lh** [nondanee/weiboPicDownloader#50]
Hi there,

Thank you so much for maintaining this repository, which is really convenient.
However, it has to download all images for a userID and every time I have to check them one by one to see which one is newly added. Can you please help add one more option, which can download images/videos from a specific date on, and of course if not specified, it download all of them from the beginning.

Thanks again!

**Comment by nondanee** [comment]
Use the `-b` option, refer to #40

**Comment by hao-lh** [comment]
Thanks a lot! That's definitely what I am looking for, but this requires checking the blog every time and check its id, thus timestamp possibly could be more convenient.

Also, could you help clarify on Usage/Optional arguments section, whether id is included or not, that means whether the range is closed [] or open (). 
> -b boundary mid/bid range of weibos (format: id:id between, :id before, id: after, id certain, : all)

Thanks again!

**Comment by nondanee** [comment]
Because I can only get the post date but not the accurate time, so can not achieve timestamp filtering

https://github.com/nondanee/weiboPicDownloader/blob/7cec7ae43234896bd85b800e9c8954b7ce58db4e/weiboPicDownloader.py#L233

It should be a closed interval []

**Comment by hao-lh** [comment]
Thank you so much for your quick response.
I think that should also help. Finding the blog date is much easier than finding the blog id, right?
So I was wondering if this tool can add one more option such as -t, so users can use it like -b option:
1. -t :20191129, which would download all images in blogs up to 20191129 (interval closed)
2. -t 20191129:, which would download all images in blogs from 20191129 (interval closed)

**Comment by nondanee** [comment]
I will let `-b`option support parsing time id like `@20191129:@20191205`

**Comment by hao-lh** [comment]
Thanks, please let me know when it is ready :)

**Comment by nondanee** [comment]
ready now :)

**Comment by hao-lh** [comment]
This is exactly what I wanted, and I tested this on my laptop it works great!
Thank you so much!
