### ISSUE TITLE
Adding at most 18 images support for single blog

### ISSUE THREAD

**Issue by hao-lh** [nondanee/weiboPicDownloader#51]
HI there,

Weibo has supported to allow users upload at most 18 images for a single blog, I checked with the latest code, seems still does not support this?

Could you help adding this feature support as well? Thanks!

**Comment by nondanee** [comment]
the code has no limitation on the max number of images
it depends on the response from weibo api

i can do nothing but wait for weibo official completing 18-image feature on its mobile site

**Comment by hao-lh** [comment]
Oh, then is there any way to check the returned intermediate data and see if it has supported at mast 18-images?
Thanks again!

**Comment by nondanee** [comment]
The 'pic_num' field will indicate 18-image
```json
"pic_num": 18,
```
But now the 'pics' field only lists information for first 9 images

You can use check it by this condition 
```python
len(mblog['pics']) == mblog['pic_num']
```

**Comment by hao-lh** [comment]
Thanks. So FYI, images are returned by Python list mblog['pics'] which would contain only the first 9 images, and this is due to the API limitation for m.weibo?

**Comment by nondanee** [comment]
Yes. Now the user's profile page (`https://m.weibo.cn/u/<uid>`) on weibo mobile site can not show 18 images correctly.

**Comment by hao-lh** [comment]
Thank you so much.
The is there any other possible means, I seen there are some 3rd party clients on iOS store which also have this feature.

**Comment by nondanee** [comment]
I have no idea
