### ISSUE TITLE
[Feature Request] Option to download videos only

### ISSUE THREAD

**Issue by Taemaly** [nondanee/weiboPicDownloader#53]
Please add option to skip photos and download videos only.
Thank you

**Comment by nondanee** [comment]
Sorry, I'm afraid this feature is off topic with "weibo**Pic**Downloader" 😂

You can modify the code by yourself

https://github.com/nondanee/weiboPicDownloader/blob/4406fbc0efca8e06e118d202bc2a7fab646bb244/weiboPicDownloader.py#L249

Just replace Line 249 with `pass`

```diff
-                                resources.append(merge({'url': pic['large']['url'], 'index': index, 'type': 'photo'}, mark))
+                                pass
```

Hope it can help you
