### ISSUE TITLE
下载失败自动重试

### ISSUE THREAD

**Issue by kybom** [nondanee/weiboPicDownloader#6]
下载失败可否自动重试2次，现在还需要手动确认
![default](https://user-images.githubusercontent.com/24692485/37443146-30c051a2-2845-11e8-90e0-3c334361a890.png)

**Comment by nondanee** [comment]
是重试2次后直接放弃吗？

**Comment by kybom** [comment]
是的

**Comment by nondanee** [comment]
加上了，试试看呗😀
